name: Update lock and Cache

on:
  # Testing, replace push with cron
  push:
  workflow_dispatch:
    inputs:
      forcerefresh:
        description: 'Force Refresh'
        required: false
        type: boolean

jobs:
  ciUpdate:
    name: Update and Cache
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            trusted-users = root build
            substituters = https://nixos-sbc.cachix.org/ https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixos-sbc.cachix.org-1:XMK0HnQmmGIt1lYy1y+JsxLpHVaSTRRWvd6T6cU+I2M=
            builders = ssh-ng://builder@hourai.kangaroo-tetra.ts.net aarch64-linux /home/runner/.ssh/githubci 1 1 benchmark,big-parallel,gccarch-armv8-a,kvm,nixos-test - c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSVBhOUxMTjdHTWhLVDkySGtyT1RFYjVjMmdvazVhOFE1Yzk2SWV3cERvcGcgcm9vdEBob3VyYWkK
      # Direct reachability is only available over IPv6.
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:srht-build
      - name: Update and Cache
        env:
          CI_FORCE_REFRESH: ${{ inputs.forcerefresh }}
          CI_GIT_EMAIL: ${{ vars.CI_GIT_EMAIL }}
        run: |
          (umask 0066; mkdir -p $HOME/.ssh)
          (umask 0077; echo "${{ secrets.NIX_BUILDER_SSH_KEY }}" > $HOME/.ssh/githubci)
          bash ./lib/flake-ci/check-update-changes.sh
